trigger:
  branches:
    include:
      - main  # Update if your default branch is different

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_VM_HOST: 'your-vm-ip'  # Replace with your actual Azure VM IP
  AZURE_VM_USER: 'srivallabha'  # Your actual VM username
  JAR_NAME: 'spring-petclinic-3.5.0-SNAPSHOT.jar'
  SOURCE_JAR_PATH: 'target/spring-petclinic-3.5.0-SNAPSHOT.jar'
  DEST_JAR_PATH: '/home/srivallabha/app.jar'

steps:

  - task: Maven@3
    displayName: '🔧 Build with Maven'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      options: '-Dmaven.test.skip=false'

  - script: |
      echo "📦 Listing build artifacts..."
      ls -lh target/
    displayName: 'List JAR Output'

  - task: CopyFilesOverSSH@0
    displayName: '📤 Copy JAR to Azure VM'
    inputs:
      sshEndpoint: 'Azure-VM-SSH'  # Must be created in Azure DevOps → Service Connections
      sourceFolder: '$(System.DefaultWorkingDirectory)/target'
      contents: '**/*.jar'
      targetFolder: '/home/srivallabha'

  - task: SSH@0
    displayName: '⚙️ Run Ansible Playbook on Azure VM'
    inputs:
      sshEndpoint: 'Azure-VM-SSH'
      runOptions: 'commands'
      command: |
        cd /home/srivallabha
        ansible-playbook -i ansible/hosts ansible/playbook.yml

  - script: |
      echo "✅ Deployment complete!"
    displayName: 'Done'
